use std::{borrow::Cow, sync::Arc};
use crate::graphics::{bind_group::BindGroupLayoutBuilder, primitive::Primitive, handler::ResourceBuilder, vertex::VertexLayoutBuilder};

/// Encapsulates the builders generated by a ShaderSpec to create layouts used by a pipeline/shader
#[derive(Clone, Debug)]
pub struct LayoutBuilders {
    pub vertex: Option<VertexLayoutBuilder>,
    pub instance: Option<VertexLayoutBuilder>,
    // bind_group: Vec<BindGroupLayoutBuilder>
}

#[derive(Clone, Debug)]
pub struct ShaderSpec {
    pub shader_builder: ShaderModuleBuilder,
    pub vs_main: String,
    pub fs_main: String,
    pub vertex_attrs: Vec<(u32, wgpu::VertexFormat)>,
    pub instance_attrs: Vec<(u32, wgpu::VertexFormat)>,
    pub bg_layouts: Vec<BindGroupLayoutBuilder>,
}

impl ShaderSpec {
    /// create the vertex layout from the provided attributes
    pub fn build_vertex_layouts(&self) -> LayoutBuilders {
        let mut builders = LayoutBuilders {
            vertex: None,
            instance: None,
        };

        // vertex attributes
        if !self.vertex_attrs.is_empty() {
            let mut vertex_layout_builder = VertexLayoutBuilder::new(wgpu::VertexStepMode::Vertex)
                .with_label(&format!("{}::vertex_layout", self.shader_builder.path));

            for (location, format) in &self.vertex_attrs {
                vertex_layout_builder.add_attribute(location.clone(), format.clone());
            }
            builders.vertex = Some(vertex_layout_builder);
        }

        // instance attributes
        if !self.instance_attrs.is_empty() {
            let mut instance_layout_builder = VertexLayoutBuilder::new(wgpu::VertexStepMode::Instance)
                .with_label(&format!("{}::instance_layout", self.shader_builder.path));

            for (location, format) in &self.instance_attrs {
                instance_layout_builder.add_attribute(location.clone(), format.clone());
            }
            builders.instance = Some(instance_layout_builder);
        };

        builders
    }

    /// validate that an entity can be drawn with this shader
    pub fn _validate(&self, _entity: &Primitive) -> bool {
        return true;
    }
}

#[derive(Clone, Debug)]
pub struct ShaderSpecBuilder {
    pub path: String,
    pub vertex_attrs: Vec<(u32, wgpu::VertexFormat)>,
    pub instance_attrs: Vec<(u32, wgpu::VertexFormat)>,
    pub bg_layouts: Vec<BindGroupLayoutBuilder>,
}

impl ShaderSpecBuilder {
    pub fn new(path: &str) -> Self {
        Self {
            path: path.to_string(),
            vertex_attrs: Vec::new(),
            instance_attrs: Vec::new(),
            bg_layouts: Vec::new(),
        }
    }

    pub fn with_vertex_attribute(mut self, location: u32, format: wgpu::VertexFormat) -> Self {
        self.vertex_attrs.push((location, format));
        self
    }

    pub fn with_instance_attribute(mut self, location: u32, format: wgpu::VertexFormat) -> Self {
        self.instance_attrs.push((location, format));
        self
    }

    pub fn with_bg_layout(mut self, layout: BindGroupLayoutBuilder) -> Self {
        self.bg_layouts.push(layout);
        self
    }
}

impl ResourceBuilder for ShaderSpecBuilder {
    type Output = ShaderSpec;
    type Context = ();

    fn build(&self, _context: Arc<()>) -> Result<ShaderSpec, String> {
        let shader_source = match std::fs::read_to_string(&self.path) {
            Ok(source) => source,
            Err(e) => {
                return Err(format!("Failed to read shader file '{}': {e}", self.path));
            }
        };

        // Shader reflection done here

        Ok(ShaderSpec {
            shader_builder: ShaderModuleBuilder { path: self.path.clone(), source: shader_source },
            fs_main: "fs_main".to_string(),
            vs_main: "vs_main".to_string(),
            vertex_attrs: self.vertex_attrs.clone(),
            instance_attrs: self.instance_attrs.clone(),
            bg_layouts: self.bg_layouts.clone(),
        })
    }
}

#[derive(Clone, Debug)]
pub struct ShaderModuleBuilder {
    pub path: String,
    pub source: String,
}

impl ResourceBuilder for ShaderModuleBuilder {
    type Context = wgpu::Device;
    type Output = Arc<wgpu::ShaderModule>;

    fn build(&self, device: Arc<wgpu::Device>) -> Result<Self::Output, String> {
        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some(format!("{}", self.path).as_str()),
            source: wgpu::ShaderSource::Wgsl(Cow::Borrowed(&self.source)),
        });

        println!("[Shader Module] Created new shader module from path {}", self.path);

        Ok(Arc::new(shader))
    }
}